### ISSUE TITLE
don't work in android 4.2.2

### ISSUE THREAD

**Issue by djamah** [sarahgoldman/cordova-print-pdf-plugin#3]
I use the plugin from the branch "google-cloud-print". But my app crashes with an error:

1105-1122/com.App.Tablet E/AndroidRuntime﹕ FATAL EXCEPTION: pool-1-thread-1
    java.lang.NoClassDefFoundError: android.print.PrintManager
            at com.sgoldm.plugin.printPDF.PrintPDF$2.run(PrintPDF.java:111)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)

Help, please, what am I doing wrong?

**Comment by sarahgoldman** [comment]
Are you sure you checked out the google-cloud-print branch? There is no instance of android.print.PrintManager in that branch. You can verify that you pulled google-cloud-print branch by looking in the src/android directory, you should find the CloudPrintDialog.java class.

**Comment by sarahgoldman** [comment]
Try reinstalling the plugin from the master branch. I have just combined the two android printing methods into the master branch. It will use native printing when available, and will fallback to google cloud print for 4.3 and less. The latest version with this change has been published to npm. Let me know if you have any trouble implementing this. I am going to remove the google-cloud-print branch as it is no longer needed.
